#!/bin/sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Tmux
rm -rf $HOME/.config/tmux
ln -s $DOTFILES/tmux $HOME/.config/tmux


if [ ! -d $HOME/.tmux/plugins/tpm ] ; then
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi

# Phpactor
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

# Scripts
mkdir -p $HOME/.local/bin

ln -sf $DOTFILES/scripts/tmx $HOME/.local/bin/tmx

